# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G -Xms1G -XX:+UseG1GC -XX:+DisableExplicitGC
org.gradle.parallel=true
org.gradle.workers.max=2
org.gradle.daemon=true
org.gradle.caching=false
org.gradle.configureondemand=true


# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=0.1.0.0
mod_id=aquaaspect
mod_name=AquaAspect
mod_description=A mod that adds Aqua Aspect, a new enchantment which deals extra damage to nether mobs and endermen.
maven_group=com.footdablit2310.aquaaspect

# Dependencies
fabric_api_version=0.141.4+1.21.11