license="${mod_license}"

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/Footdablit2310/Aquaaspect/issues"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Footdablit2310"
description='''
Example mod description.
'''
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
   versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

